// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: followFeed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const followFeed = `-- name: FollowFeed :one
INSERT INTO feedFollowed (feed_id, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING feed_id, user_id, created_at, updated_at
`

type FollowFeedParams struct {
	FeedID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) FollowFeed(ctx context.Context, arg FollowFeedParams) (Feedfollowed, error) {
	row := q.db.QueryRowContext(ctx, followFeed,
		arg.FeedID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feedfollowed
	err := row.Scan(
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
